In [22]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\ritik\OneDrive\Desktop\store_customers.csv")

In [23]:
df

     CustomerID Gender   Age  Annual Income (k$)  Spending Score (1-100)
0          1000      M  39.0                59.9                    58.0
1          1001      M  34.0                48.4                    37.0
2          1002      F  40.0                70.5                    26.0
3          1003      F  47.0                81.1                    30.0
4          1004      F  33.0                42.1                    58.0
..          ...    ...   ...                 ...                     ...
995        1995      M  80.0               133.3                     1.0
996        1996      M  44.0                82.6                    40.0
997        1997      F  46.0                67.7                    26.0
998        1998      F  28.0                45.7                    59.0
999        1999      M  67.0               107.8                     1.0

[1000 rows x 5 columns]

In [24]:
df.rename(columns={
    "Annual Income (k$)": "Annual_Income",
    "Spending Score (1-100)": "Spending_Score"
}, inplace=True)

In [25]:
df

     CustomerID Gender   Age  Annual_Income  Spending_Score
0          1000      M  39.0           59.9            58.0
1          1001      M  34.0           48.4            37.0
2          1002      F  40.0           70.5            26.0
3          1003      F  47.0           81.1            30.0
4          1004      F  33.0           42.1            58.0
..          ...    ...   ...            ...             ...
995        1995      M  80.0          133.3             1.0
996        1996      M  44.0           82.6            40.0
997        1997      F  46.0           67.7            26.0
998        1998      F  28.0           45.7            59.0
999        1999      M  67.0          107.8             1.0

[1000 rows x 5 columns]

In [26]:
# Approximate Annual Spending
df["Annual_Spending"] = df["Annual_Income"] * df["Spending_Score"]

# Approximate Purchase Frequency
df["Purchase_Frequency"] = df["Spending_Score"] / 2

In [11]:
df

,CustomerID,Gender,Age,Annual_Income,Spending_Score,Purchase_Frequency
0,1000,M,39.0,59.9,58.0,29.0
1,1001,M,34.0,48.4,37.0,18.5
2,1002,F,40.0,70.5,26.0,13.0
3,1003,F,47.0,81.1,30.0,15.0
4,1004,F,33.0,42.1,58.0,29.0
...,...,...,...,...,...,...
995,1995,M,80.0,133.3,1.0,0.5
996,1996,M,44.0,82.6,40.0,20.0
997,1997,F,46.0,67.7,26.0,13.0
998,1998,F,28.0,45.7,59.0,29.5
999,1999,M,67.0,107.8,1.0,0.5

In [28]:
df_final = df[["Annual_Spending", "Purchase_Frequency"]]
df_final

     Annual_Spending  Purchase_Frequency
0             3474.2                29.0
1             1790.8                18.5
2             1833.0                13.0
3             2433.0                15.0
4             2441.8                29.0
..               ...                 ...
995            133.3                 0.5
996           3304.0                20.0
997           1760.2                13.0
998           2696.3                29.5
999            107.8                 0.5

[1000 rows x 2 columns]